extends: airbnb-base
globals:
  E2E: readonly
  PRODUCTION: readonly
rules:
  no-restricted-syntax: 'off'
  prefer-destructuring: warn
  curly:
    - error
    - all
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: false
  padding-line-between-statements:
    - error
    - blankLine: never
      prev: "*"
      next: "*"
    - blankLine: always
      prev: "*"
      next: function
    - blankLine: always
      prev:
        - function
        - import
        - export
        - cjs-import
        - cjs-export
      next: "*"
    - blankLine: never
      prev:
        - import
        - cjs-import
      next:
        - import
        - cjs-import
    - blankLine: always
      prev: "*"
      next:
        - export
        - cjs-export
    - blankLine: any
      prev: multiline-expression
      next: "*"
  no-multiple-empty-lines:
    - error
    - max: 1
      maxEOF: 0
      maxBOF: 0
  no-use-before-define:
    - error
    - functions: false
  object-curly-spacing:
    - error
    - never
  arrow-parens:
    - error
    - always
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - src/**/*-test.js
        - e2e/*-e2e.js
        - webpack.config.js
overrides:
  - files:
      - "*-test.js"
      - "*-e2e.js"
    env:
      mocha: true
    rules:
      prefer-arrow-callback: 'off'
      func-names: 'off'
  - files: "*-e2e.js"
    env:
      browser: true
  - files:
      - "*background.js"
      - "*content.js"
      - "*popup-tab-switcher.js"
      - "**/settings/index.js"
    env:
      browser: true
      webextensions: true
