env:
  browser: true
  webextensions: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - import
  - prettier
  - mocha-no-only
extends:
  - airbnb-base
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:prettier/recommended
settings:
  import/resolver:
    node:
      extensions: ['.js', '.jsx', '.ts', '.tsx']
  react:
    version: detect
rules:
  prefer-destructuring: warn
  curly: [error, all]
  brace-style: [error, 1tbs, {allowSingleLine: false}]
  no-multiple-empty-lines: [error, {max: 1, maxEOF: 0, maxBOF: 0}]
  no-use-before-define: [error, {functions: false}]
  '@typescript-eslint/no-use-before-define': [error, {functions: false}]
  '@typescript-eslint/explicit-function-return-type': off
  prefer-arrow-callback: off
  object-curly-spacing: [error, never]
  arrow-parens: [error, always]
  import/extensions: off
  import/no-extraneous-dependencies: [error, {devDependencies: ["./**/*e2e.js", "./**/*test.js", 'webpack.config.js']}]
  react/prop-types: off
  react/display-name: off
  mocha-no-only/mocha-no-only: [error]
overrides:
  - files: ['webpack.config.js']
    rules:
      '@typescript-eslint/no-var-requires': off
      '@typescript-eslint/camelcase': off
      '@typescript-eslint/no-empty-function': off
