env:
  browser: true
  webextensions: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - import
  - mocha-no-only
extends:
  - airbnb-base
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:react/recommended
settings:
  import/resolver:
    node:
      extensions: ['.js', '.jsx', '.ts', '.tsx']
rules:
  prefer-destructuring: off
  curly: [error, all]
  brace-style: [error, 1tbs, {allowSingleLine: false}]
  no-param-reassign: off
  no-multiple-empty-lines: [error, {max: 1, maxEOF: 0, maxBOF: 0}]
  no-use-before-define: [error, {functions: false}]
  '@typescript-eslint/no-use-before-define': [error, {functions: false}]
  '@typescript-eslint/interface-name-prefix': [warn, always]
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-unused-vars': [error, {argsIgnorePattern: '^_', varsIgnorePattern: '^_'}]
  '@typescript-eslint/member-delimiter-style': off
  '@typescript-eslint/no-empty-function': [warn]
  '@typescript-eslint/camelcase': [warn]
  prefer-arrow-callback: off
  object-curly-spacing: [error, never]
  arrow-parens: [error, always]
  import/extensions: off
  import/no-extraneous-dependencies:
    [error, {devDependencies: ['./**/*test.js', 'webpack.config.js']}]
  import/prefer-default-export: off
  react/jsx-uses-vars: error
  react/react-in-jsx-scope: off
  react/no-unknown-property: off
  react/prop-types: off
  react/display-name: off
  comma-dangle: off
  operator-linebreak: off
  implicit-arrow-linebreak: off
  function-paren-newline: off
  quotes: off
  object-curly-newline: off
  indent: off
  max-len: off
  no-unused-expressions: off
  semi: off
  consistent-return: off
  class-methods-use-this: off
overrides:
  - files: ['webpack.config.js']
    rules:
      '@typescript-eslint/no-var-requires': off
      '@typescript-eslint/camelcase': off
      '@typescript-eslint/no-empty-function': off
