name: Main
on: push
jobs:
  test:
    name: Checks sources with linter, run tests and build for production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      - name: Linter
        run: npm run lint
      - name: Unit tests
        run: npm run test
      - name: Build for production
        run: npm run build:prod
      - name: End-to-end tests
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: npm run test:e2e:ci
