name: Main
on: push
jobs:
  test:
    name: Checks sources with linter, run tests and build for production
    runs-on: ubuntu-latest
    steps:
      - name: Please run
        run: echo "hello world"
